config/routes.rb
Rails.application.routes.draw do
  resources :userchats
  devise_for :users
  resources :chats
  root 'chats#index'
  resources :users
  get 'search', to: 'search#index'
  resources :groups

  # get 'sign_out', to: 'users#sign_out'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/group.rb
class Group < ApplicationRecord
    has_and_belongs_to_many :users
    has_many :chats
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :find_group, only: %i[show update edit destroy]
  # before_action :set_query
  def index
    # debugger
    if params[:q]
      @query = Group.ransack(params[:q])
      @searched = @query.result(distinct: true)
    end
    
    if @searched
      @groups = @searched
    else
      @groups = Group.all
    end

  end

  def show
    @chat = Chat.new
    @users = User.all
    @searched = []
    @chats = Chat.where(group_id: params[:id])
    # debugger
    @id = params[:id]

    @chat.group_id = params[:id]
    # debugger

    @username = current_user.email.split("@")[0].capitalize() || 'Guest'
    @chat.username = current_user.email.split("@")[0].capitalize() || 'Guest'

    # If the page number isn't specified in the query parameters, show the last page
    

    if params[:q]
      @query = Chat.ransack(params[:q])
      @searched = @query.result(distinct: true)
      # debugger
    end

    total_pages = @chats.paginate(page: params[:page], per_page: 16).total_pages

    if params[:page].blank?
      @chats = Chat.paginate(page: total_pages, per_page: 16).order('created_at ASC').where(group_id: params[:id])
    else
      @chats = Chat.paginate(page: params[:page], per_page: 16).order('created_at ASC').where(group_id: params[:id])
    end
  
    if params["format"]
      @id = params["format"].to_i
      @chat = Chat.find(@id)
    end
    
  end

  def create
    debugger
    @group = Group.create(group_params)
    @group.user_ids = current_user.id
    if @group.save
      format.html { redirect_to group_url(@group), notice: "Group was successfully created." }
      format.json { render :show, status: :created, location: @group }
    else
      format.html { render :new, status: :unprocessable_entity }
      format.json { render json: @group.errors, status: :unprocessable_entity }
    end
  end
  
  def update
    # debugger
    @chat = Chat.new
    @chat.message = params[:group][:message]
    @chat.user_id = current_user.id
    @chat.group_id = params[:id]
    @chat.username = current_user.email.split("@")[0].capitalize() || 'Guest'
    if @chat.save
      # debugger
      # redirect_to group_url(@group)
      redirect_to group_url(@group)
    end
    # respond_to do |format|
    #   if @chat.save
    #     format.html { redirect_to group_url(@group), notice: "Group was successfully updated." }
    #     format.json { render :show, status: :ok, location: @group }
    #   else
    #     format.html { render :edit, status: :unprocessable_entity }
    #     format.json { render json: @group.errors, status: :unprocessable_entity }
    #   end
    # end
    
  end

  def edit
  end

  def new
    @group = Group.new
  end

  def destroy
    @group.destroy
    redirect_to root_path, notice: 'group was successfully destroyed.'
  end

  # def set_query
  #   @query = Group.ransack(params[:q])
  # end
  private

    def find_group
      @group = Group.find(params[:id])
    end

    def group_params
      params.require(:group).permit(:name, :description, :message, :username)
    end
end

app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>
  <% if group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<div id="<%= dom_id group %>">

  <p>
    <strong>Id:</strong>
    <%= group.id %>
  </p>

  <p>
    <strong>name:</strong>
    <%= group.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= group.description %>
  </p>

</div>

app/views/groups/_search.html.erb
<%= search_form_for(@query, url: groups_path, method: :get, class: 'd-flex') do |f| %>
    <%= f.search_field :name_i_count_any, placeholder: "Search..." , class: "srch me-2 form-control" %>
    <%= f.submit "Search!", class: "btn2 btn btn-outline-success"  %>
<% end %>
<br>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Show this group", @group %> |
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/index.html.erb
<center>
<p style="color: green"><%= notice %></p>

<h1>All Groups</h1>

<%ender "search"%>
<div id="groups">
  <% @groups.each do |group| %>
    <% if group.id == 4 %>
      
    <% else %>
      <%= render group %>
      <p>
        <%= link_to "JOIN", group %>
      </p>
      <hr>
    <% end %>
  <% end %>
</div>
<hr>
<%= link_to "Create group", new_group_path %>
</center>

app/views/groups/new.html.erb
<br>
<br>
<center>
<h1>New group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Back to groups", groups_path %>
</div>
</center>

app/views/groups/show.html.erb
<%= javascript_tag do %>
  let username = '<%= j @username %>';
<% end %>
<div class="container-fluid">
  <div class="row">
    <div class="col-3 col-md-2 bg-dark full-height sidebar">

      <div class="sidebar-content">
        <%# <input type="text" class="form-control sidebar-form" placeholder="Lock click here to unlock" required /> %>
        <h4 class="text-white mt-5 text-center">Hello <%= @username%></h4>
      </div>

      <div class="text-white mt-5 text-center">
        <% for user in @users%>
          <%= user["email"].split("@")[0].capitalize() %><br>
        <% end %>
      </div>
    </div>

    <div class="col-9 col-md-8 bg-light full-height">
      <div class="container-fluid">
        <div class="chat-box py-2">
          <h4 class="username d-none mb-3"></h4>
          <% @chats.each do |chat| %>
            <div class="row">
              <div class="col-12">
                <% if @username.capitalize() == chat.username.capitalize()  %>
                  <div class="chat d-inline-block text-left text-white mb-2 float-right red">


                    <div class="chat-bubble">
                      <div class="d-flex align-items-center chat-style mb-2">
                        <small class="chat-username mr-2"><%= chat.username %></small>
                        <div class="dropdown ml-auto">
                          <button class="btn btn-dark" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-ellipsis-v text-white"></i>
                          </button>
                          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                            <%= link_to "Edit", chats_path(chat), class: 'dropdown-item' %>
                            <%= form_for chat, url: chat_path(chat), method: :delete, data: { confirm: 'Are you sure?' } do |f| %>
                              <%= f.button type: 'submit', class: 'dropdown-item' do %>
                                Delete
                              <% end %>
                            <% end %>
                          </div>
                        </div>
                      </div>
                      <p class="m-0 chat-message"><%= chat.message %></p>
                    </div>


                  </div>
                <% else %>
                  <div class="chat bg-secondary d-inline-block text-left text-white mb-2">
                    <div class="chat-bubble chat-style">
                      <small class="chat-username"><%= chat.username %></small>
                    </div>
                      <p class="m-0 chat-message"><%= chat.message %></p>
                    
                  </div>
                  <div class="clear"></div>
                <% end %>


              </div>
            </div>
          <% end %>
        </div>
        <div class="chat-text-input">
          <%= form_with(model: @group, remote: true, format: :json, id: 'group-form') do |form| %>
            <% if @group.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@group.errors.count, "error") %> prohibited this chat from being saved:</h2>
                <ul>
                  <% @group.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
            <%= will_paginate @chats %>
            <div class="field position-relative">
              <%= form.text_field :message, id: :message, class: "form-control", required: true %>
              <%= form.hidden_field :username, id: :username %>
            </div>
          <% end %>
        </div>
        
      </div>
    </div>


    <div class="col-3 col-md-2 bg-white full-height sidebar float-end">
      <div class="text-black mt-5 text-center">
        <div class="chat d-inline-block text-left text-white mb-2 float-right red">

          <% if @searched.count <  @chats.count%>
            <% @searched.each do |chat| %>
            <div class="col-12 ">
              <div class="chat bg-dark d-inline-block text-left text-white mb-2 ">
                <div class="chat-bubble " style= "display: flex; justify-content; space-between">
                  <div>
                    <small class="chat-username "><%= chat.username %></small>
                    
                  </div>
                  
                </div>
                
              </div>
              
            </div>
          <% end %>

          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>