config/routes.rb
Rails.application.routes.draw do
  resources :userchats
  devise_for :users
  resources :chats
  root 'chats#index'
  resources :users
  get 'search', to: 'search#index'
  resources :groups

  # get 'sign_out', to: 'users#sign_out'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/userchat.rb
class Userchat < ApplicationRecord
    belongs_to :user
end

app/controllers/userchats_controller.rb
class UserchatsController < ApplicationController
  before_action :set_userchat, only: %i[ show edit update destroy ]

  # GET /userchats or /userchats.json
  def index
    # debugger
    @userchats = Userchat.all
    if $receiver && params[:format]
      @userchat = Userchat.find(params[:format])
    elsif params[:format] 
      $receiver = User.find(params[:format])
      @receiver_name  = $receiver.email.split("@")[0].capitalize() || 'Guest'
    end
   
    @userchat = Userchat.new
    @users = User.all
    @searched = []

    @username = current_user.email.split("@")[0].capitalize() || 'Guest'
    @userchat.username = current_user.email.split("@")[0].capitalize() || 'Guest'

    # If the page number isn't specified in the query parameters, show the last page
    
    if params[:q]
      @query = Userchat.ransack(params[:q])
      @searched = @query.result(distinct: true)
      # debugger
    end

    # total_pages = @userchats.paginate(page: params[:page], per_page: 16).total_pages
    # # debugger
    # if params[:page].blank?
    #   @userchats = Userchat.paginate(page: total_pages, per_page: 16).order('created_at ASC').where(group_id: 4)
    # else
    #   @userchats = Userchat.paginate(page: params[:page], per_page: 16).order('created_at ASC').where(group_id: 4)
    # end
  
    # if params["format"]
    #   @id = params["format"].to_i
    #   @chat = Userchat.find(@id)
    # end
    
    render :index, locals: { username: @username }

  end

  def fake_index

  end

  # GET /userchats/1 or /userchats/1.json
  def show

    
    @userchats = Userchat.all
    if params[:params
      $receiver = User.find(params[:format])
      @receiver_name  = $receiver.email.split("@")[0].capitalize() || 'Guest'
    end
   
    @userchat = Userchat.new
    @users = User.all
    @searched = []

    @username = current_user.email.split("@")[0].capitalize() || 'Guest'
    @userchat.username = current_user.email.split("@")[0].capitalize() || 'Guest'

    # If the page number isn't specified in the query parameters, show the last page
    
    if params[:q]
      @query = Userchat.ransack(params[:q])
      @searched = @query.result(distinct: true)
      # debugger
    end

    # total_pages = @userchats.paginate(page: params[:page], per_page: 16).total_pages
    # # debugger
    # if params[:page].blank?
    #   @userchats = Userchat.paginate(page: total_pages, per_page: 16).order('created_at ASC').where(group_id: 4)
    # else
    #   @userchats = Userchat.paginate(page: params[:page], per_page: 16).order('created_at ASC').where(group_id: 4)
    # end
  
    # if params["format"]
    #   @id = params["format"].to_i
    #   @chat = Userchat.find(@id)
    # end
    
    render :index, locals: { username: @username }

  end

  # GET /userchats/new
  def new
    @userchat = Userchat.new
  end

  # GET /userchats/1/edit
  def edit
    fake_index($receiver, @userchat)
  end

  # POST /userchats or /userchats.json
  def create
    # debugger
    @userchat = Userchat.new(userchat_params)
    @userchat.user_id = current_user.id
    @userchat.sender = current_user.id
    @userchat.username = current_user.email.split("@")[0].capitalize() || 'Guest'
    @userchat.receiver = $receiver.id
    
    if @userchat.save
      redirect_to userchats_path($receiver.id)
    end
  end

  # PATCH/PUT /userchats/1 or /userchats/1.json
  def update
    debugger
    @id = $receiver.id
    respond_to do |format|
      if @userchat.update(userchat_params)
        format.html { redirect_to userchat_url(@id), notice: "Userchat was successfully updated." }
        format.json { render :show, status: :ok, location: @userchat }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @userchat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /userchats/1 or /userchats/1.json
  def destroy
    @userchat.destroy
    @id = $receiver.id
    # debugger
    respond_to do |format|
      format.html { redirect_to userchats_url(@id), notice: "Userchat was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_userchat
      @userchat = Userchat.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def userchat_params
      params.require(:userchat).permit(:message, :sender, :receiver, :user_id, :username)
    end
end

app/helpers/userchats_helper.rb
module UserchatsHelper
end

app/views/userchats/_form.html.erb
<%= form_with(model: userchat) do |form| %>
  <% if userchat.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(userchat.errors.count, "error") %> prohibited this userchat from being saved:</h2>

      <ul>
        <% userchat.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :message, style: "display: block" %>
    <%= form.text_area :message %>
  </div>

  <div>
    <%= form.label :sender, style: "display: block" %>
    <%= form.number_field :sender %>
  </div>

  <div>
    <%= form.label :receiver, style: "display: block" %>
    <%= form.number_field :receiver %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/userchats/_userchat.html.erb
<div id="<%= dom_id userchat %>">
  <p>
    <strong>Message:</strong>
    <%= userchat.message %>
  </p>

  <p>
    <strong>Sender:</strong>
    <%= userchat.sender %>
  </p>

  <p>
    <strong>Resever:</strong>
    <%= userchat.receiver %>
  </p>

  <p>
    <strong>User:</strong>
    <%= userchat.user_id %>
  </p>

  <p>
    <strong>Username:</strong>
    <%= userchat.username %>
  </p>

</div>

app/views/userchats/edit.html.erb
<h1>Editing userchat</h1>

<%= render "form", userchat: @userchat %>

<br>

<div>
  <%= link_to "Show this userchat", @userchat %> |
  <%= link_to "Back to userchats", userchats_path %>
</div>

app/views/userchats/index.html.erb
<%= javascript_tag do %>
  let username = '<%= j @username %>';
<% end %>
<div class="container-fluid">
  <div class="row">
    <div class="col-3 col-md-2 bg-dark full-height sidebar">

      <div class="sidebar-content">
        <%# <input type="text" class="form-control sidebar-form" placeholder="Lock click here to unlock" required /> %>
        <h4 class="text-white mt-5 text-center">Hello <%= @username%></h4>
      </div>

      <div class="text-white mt-5 text-center">

        <% for user in @users%>
          <div class= "red" >
            <% if user.email == current_user.email %>
            <%else%>
              <%= link_to user["email"].split("@")[0].capitalize(), userchats_path(user), class: "text-white mt-5 text-center"  %><br>
            <% end %>
          </div>
        <br>
        <% end %>
        
      </div>
    </div>

    <div class="col-9 col-md-8 bg-light full-height">
      <div class="container-fluid">



        <div class="chat-box py-2">
          <h4 class="username d-none mb-3"></h4>
          <% @userchats.each do |chat| %>
            <div class="row">
              <div class="col-12">

                <% if @username.capitalize() == chat.username.capitalize()  %>
                  <div class="chat d-inline-block text-left text-white mb-2 float-right red">
                    <div class="chat-bubble">
                      <div class="d-flex align-items-center chat-style mb-2">
                        <small class="chat-username mr-2"><%= chat.username %></small>
                        <div class="dropdown ml-auto">
                          <button class="btn btn-dark" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-ellipsis-v text-white"></i>
                          </button>
                          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                            <%= link_to "Edit", edit_userchat_path(chat), class: 'dropdown-item' %>
                            <%= form_for chat, url: userchat_path(chat), method: :delete, data: { confirm: 'Are you sure?' } do |f| %>
                              <%= f.button type: 'submit', class: 'dropdown-item' do %>
                                Delete
                              <% end %>
                            <% end %>
                          </div>
                        </div>
                      </div>
                      <p class="m-0 chat-message"><%= chat.message %></p>
                    </div>


                  </div>
                <% elsif chat.username == @receiver_name %>
                  <div class="chat bg-secondary d-inline-block text-left text-white mb-2">
                    <div class="chat-bubble chat-style">
                      <small class="chat-username"><%= chat.username %></small>
                    </div>
                      <p class="m-0 chat-message"><%= chat.message %></p>
                    
                  </div>
                  <div class="clear"></div>
                <% end %>


              </div>
            </div>
          <% end %>

        </div>
        <div class="chat-text-input">
          <%= form_with(model: @userchat, remote: true, format: :json, id: 'userchat-form') do |form| %>
            <% if @userchat.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@userchat.errors.count, "error") %> prohibited this chat from being saved:</h2>
                <ul>
                  <% @userchat.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>

            <%# <%= will_paginate @userchats %>

            <div class="field position-relative">
              <%= form.text_field :message, id: :message, class: "form-control", required: true %>
              <%= form.hidden_field :username, id: :username %>
            </div>
          <% end %>

        </div>
        
      </div>
    </div>


    <div class="col-3 col-md-2 bg-white full-height sidebar float-end">
      <div class="text-black mt-5 text-center">
        <div class="chat d-inline-block text-left text-white mb-2 float-right red">

          <% if @searched.count <  @userchats.count%>
            <% @searched.each do |chat| %>
            <div class="col-12 ">
              <div class="chat bg-dark d-inline-block text-left text-white mb-2 ">
                <div class="chat-bubble " style= "display: flex; justify-content; space-between">
                  <div>
                    <small class="chat-username "><%= chat.username %></small>
                    
                  </div>
                  
                </div>
                
              </div>
              
            </div>
          <% end %>

          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/userchats/new.html.erb
<h1>New userchat</h1>

<%= render "form", userchat: @userchat %>

<br>

<div>
  <%= link_to "Back to userchats", userchats_path %>
</div>

app/views/userchats/show.html.erb
<%= javascript_tag do %>
  let username = '<%= j @username %>';
<% end %>
<div class="container-fluid">
  <div class="row">
    <div class="col-3 col-md-2 bg-dark full-height sidebar">

      <div class="sidebar-content">
        <%# <input type="text" class="form-control sidebar-form" placeholder="Lock click here to unlock" required /> %>
        <h4 class="text-white mt-5 text-center">Hello <%= @username%></h4>
      </div>

      <div class="text-white mt-5 text-center">

        <% for user in @users%>
          <div class= "red" >
            <% if user.email == current_user.email %>
            <%else%>
              <%= link_to user["email"].split("@")[0].capitalize(), userchats_path(user), class: "text-white mt-5 text-center"  %><br>
            <% end %>
          </div>
        <br>
        <% end %>
        
      </div>
    </div>

    <div class="col-9 col-md-8 bg-light full-height">
      <div class="container-fluid">



        <div class="chat-box py-2">
          <h4 class="username d-none mb-3"></h4>
          <% @userchats.each do |chat| %>
            <div class="row">
              <div class="col-12">

                <% if @username.capitalize() == chat.username.capitalize()  %>
                  <div class="chat d-inline-block text-left text-white mb-2 float-right red">
                    <div class="chat-bubble">
                      <div class="d-flex align-items-center chat-style mb-2">
                        <small class="chat-username mr-2"><%= chat.username %></small>
                        <div class="dropdown ml-auto">
                          <button class="btn btn-dark" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-ellipsis-v text-white"></i>
                          </button>
                          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                            <%= link_to "Edit", edit_userchat_path(chat), class: 'dropdown-item' %>
                            <%= form_for chat, url: userchat_path(chat), method: :delete, data: { confirm: 'Are you sure?' } do |f| %>
                              <%= f.button type: 'submit', class: 'dropdown-item' do %>
                                Delete
                              <% end %>
                            <% end %>
                          </div>
                        </div>
                      </div>
                      <p class="m-0 chat-message"><%= chat.message %></p>
                    </div>


                  </div>
                <% elsif chat.username == @receiver_name %>
                  <div class="chat bg-secondary d-inline-block text-left text-white mb-2">
                    <div class="chat-bubble chat-style">
                      <small class="chat-username"><%= chat.username %></small>
                    </div>
                      <p class="m-0 chat-message"><%= chat.message %></p>
                    
                  </div>
                  <div class="clear"></div>
                <% end %>


              </div>
            </div>
          <% end %>

        </div>
        <div class="chat-text-input">
          <%= form_with(model: @userchat, remote: true, format: :json, id: 'userchat-form') do |form| %>
            <% if @userchat.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@userchat.errors.count, "error") %> prohibited this chat from being saved:</h2>
                <ul>
                  <% @userchat.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>

            <%# <%= will_paginate @userchats %>

            <div class="field position-relative">
              <%= form.text_field :message, id: :message, class: "form-control", required: true %>
              <%= form.hidden_field :username, id: :username %>
            </div>
          <% end %>

        </div>
        
      </div>
    </div>


    <div class="col-3 col-md-2 bg-white full-height sidebar float-end">
      <div class="text-black mt-5 text-center">
        <div class="chat d-inline-block text-left text-white mb-2 float-right red">

          <% if @searched.count <  @userchats.count%>
            <% @searched.each do |chat| %>
            <div class="col-12 ">
              <div class="chat bg-dark d-inline-block text-left text-white mb-2 ">
                <div class="chat-bubble " style= "display: flex; justify-content; space-between">
                  <div>
                    <small class="chat-username "><%= chat.username %></small>
                    
                  </div>
                  
                </div>
                
              </div>
              
            </div>
          <% end %>

          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>